<script lang="ts">
    /**
     * Table of contents component for my website. Designed to work with
     * `MarkdownPostLayout.astro`.
     */
    import type { MarkdownHeading } from "astro";
    import { onMount } from "svelte";
    import { SvelteSet } from "svelte/reactivity";

    interface Props {
        /**
         * The headings (h1, h2, etc) of the post. These are automatically
         * generated by Astro.
         */
        headings: MarkdownHeading[];
    }

    const { headings }: Props = $props();

    let activeSlug: string | undefined = $state(undefined);

    // wire up intersection observer
    onMount(() => {
        // get a list of the actual HTML header elements corresponding to
        // `headings
        const targets = headings
            .map((h) => ({
                slug: h.slug,
                element: document.getElementById(h.slug),
            }))
            .filter((t): t is { slug: string; element: HTMLElement } => {
                return t.element !== null;
            });

        // the HTML headings visible at any given time
        const visible = new SvelteSet<HTMLElement>();

        // construct the IntersectionObserver
        const observer = new IntersectionObserver(
            (entries) => {
                for (const entry of entries) {
                    if (entry.isIntersecting) {
                        visible.add(entry.target as HTMLElement);
                    } else {
                        visible.delete(entry.target as HTMLElement);
                    }
                }
                // first heading in the list of headings that is visible
                const top = targets.find((t) => visible.has(t.element));
                if (top) {
                    activeSlug = top.slug;
                }
            },
            { rootMargin: "0px 0px -40% 0px", threshold: 0 },
        );

        for (const t of targets) {
            observer.observe(t.element);
        }

        return () => observer.disconnect();
    });
</script>

<!-- top-19 is kinda hacky; it is basically the distance from the top of the viewport to the location of the TOC widget, but it depends on things like the height and spacing of the nav bar.-->
<div class="mx-4 hidden xl:block sticky top-19 max-w-full">
    <div class="flex flex-col items-start min-w-40 w-fit max-w-full">
        {#each headings as heading (heading.slug)}
            <a
                href={`#${heading.slug}`}
                class={[
                    "text-xs py-0.5 px-3 border-l border-line transition-all duration-150 font-mono text-ink-tertiary w-full truncate",
                    {
                        "text-primary border-primary bg-primary/10 border-l-3":
                            activeSlug === heading.slug,
                    },
                ]}
            >
                {heading.text}
            </a>
        {/each}
    </div>
</div>
